### ISSUE TITLE
Great Tool - Get it into pip as pip deptree :)

### ISSUE THREAD

**Issue by prologic** [tox-dev/pipdeptree#1]
This is awesome! Let's see if we can get this into pip itself via `pip deptree` :)

**Comment by msabramo** [comment]
See https://github.com/pypa/pip/pull/2329 for a pip PR that proposes to add a plugin facility to pip. And then I created https://github.com/naiquevin/pipdeptree/pull/27 to make pipdeptree into such a plugin.

Comments welcome.

**Comment by therealprologic** [comment]
Awesome :) Can't wait!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by gaborbernat** [comment]
This would be a pip issue, not here.
