### ISSUE TITLE
Fail on conflicting dependencies but not circular dependencies

### ISSUE THREAD

**Issue by jaraco** [tox-dev/pipdeptree#110]
I'd like to use pipdeptree to detect conflicting dependencies - those that will cause problems with pkg_resources when imported or are otherwise not meeting their declared requirements. For that, this tool provides `--warn fail`. However, this option also causes the tool to fail on circular dependencies, which happens as a matter of course for a project that requires `jaraco.text` or `jaraco.collections` (as they depend on each other).

Probably pipdeptree should take `--on-circular` and `--on-conflicting` parameters, each accepting `pass`, `fail`, or `warn`.

**Comment by gaborbernat** [comment]
I think the failure is up to pip, if pip does not fail we should not either.
