### ISSUE TITLE
Difference with `pip check`

### ISSUE THREAD

**Issue by xuzuoyang** [tox-dev/pipdeptree#120]
I've recently encountered some cases where `pip check` cannot report all the conflicts correctly, while pipdeptree did the job (in the warning part of the output). So what is the difference between these two methods of discovering dependency conflicts?

**Comment by naiquevin** [comment]
I haven't used `pip check` at all so not sure how that works. Can you please share an example `requirements.txt` file using which I can reproduce the problem?

**Comment by xuzuoyang** [comment]
The case was on a private project, but I think I might reproduce it on another public one. I'll let you know once I made it.

**Comment by gaborbernat** [comment]
this tool is intended to display the depenency tree while pip check just checks the validity of project version constraints
