### ISSUE TITLE
No output for some packages

### ISSUE THREAD

**Issue by rwarren** [tox-dev/pipdeptree#124]
Some packages result in silent failures. One example:
```
$ pipdeptree -p qgrid

$
```
This package actually has a quite a large dependency tree.

**Comment by rwarren** [comment]
Is the issue that `qgrid` indirectly reads its requirements from a file? See here:

https://github.com/quantopian/qgrid/blob/master/setup.py#L146

FWIW, I can get the (huge) dep tree with [johnnydep](https://pypi.org/project/johnnydep/), but it takes *forever*, so I expect it is doing something like recursively executing the various {{setup.py}} files to do it.

**Comment by gaborbernat** [comment]
Seems there hasn't been any push for this for 3 years, so closing for now.
