### ISSUE TITLE
Success code returned on missing packages

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/pipdeptree#127]
I was totally confused by output of pipdeptree when I tried to call it with `pipdeptree -p ansiblelint`, as it listed not deps and returned as success.

It was my mistake to mention module name instead of correct packaga name `ansible-lint` but clearly returning 0 is a bug, as a missing package should clearly return an error.

**Comment by naiquevin** [comment]
Ok, I had not thought about exit codes that way. Currently, pipdeptree only exits with non-zero in case of conflicts (that too, only if id `-w fail` option is specified). 

What's the use case you are trying to solve with pipdeptree?

**Comment by gaborbernat** [comment]
PR for this welcome.
