### ISSUE TITLE
feature: ability to output mermaid/dot/graphviz dependency graphs

### ISSUE THREAD

**Issue by ssbarnea** [tox-dev/pipdeptree#129]
[Mermaid](https://mermaid-js.github.io/mermaid/#/) is an open-souce graph maker that can easily be integrated in any web page and also with documentation build tools (sphinx, markdown based tools,...)

Example of graph:

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

Note: there is also a feature request to enable mermaid markdown extension on github, which would render it directly.

**Comment by gaborbernat** [comment]
PR welcome.

**Comment by kdeldycke** [comment]
`dot` and `graphviz` are already implemented. I proposed a PR which implements Mermaid output at: https://github.com/tox-dev/pipdeptree/pull/195

If this PR is merged upstream, them this issue can be closed.
