### ISSUE TITLE
List installed packages that are not dependencies of another installed package.

### ISSUE THREAD

**Issue by clysto** [tox-dev/pipdeptree#141]
using homebrew I can simply use `brew leaves` to show all installed formulae that are not dependencies of another installed formula.

How to do the same thing using pipdeptree?

Something equivalent to this:
```bash
pipdeptree --r -a | rg -U "^[^ ].*\n[^ ].*\n" | sed -n "p;n"
```

**Comment by naiquevin** [comment]
There's no direct way to do this. Does the above command work? 

Also, what's `rg`?

**Comment by clysto** [comment]
`rg` is `ripgrep` similar to `grep` command. It support mutiline search.

<img width="597" alt="截屏2020-12-24 上午9 34 24" src="https://user-images.githubusercontent.com/38179369/103048941-37b1aa00-45cb-11eb-9f2c-788e377c9e38.png">

If pipdeptree can do this in a direct way, it will be more convenient😊.

**pipdeptree is a awsome tool!**

**Comment by naiquevin** [comment]
Thanks for the kind words :-) It should be quite simple to implement. Curious to understand the use case for this. In what way do you use these _leaf_ packages output?

**Comment by clysto** [comment]
Sometimes I want to get the specific packages I installed, and I can safely delete the packages listed by leaves.

**Comment by gaborbernat** [comment]
This sounds like -r combined with https://github.com/tox-dev/pipdeptree/issues/89
