### ISSUE TITLE
Is it possible to run pipdeptree from code ?

### ISSUE THREAD

**Issue by bekraupov** [tox-dev/pipdeptree#145]
i.e. like an API request? 

this way i dont have to call it via external cmd way like "pipdeptree pacakge -json"

**Comment by naiquevin** [comment]
No, it's not possible at present as there's no function in the module with a fn signature similar to the command line interface.

**Comment by muellerzr** [comment]
Yes, there is. I did so in `dependency-checker` here: https://github.com/muellerzr/dependency_checker/blob/master/dependency_checker/checker.py#L14

**Comment by gaborbernat** [comment]
I'm not sure what this API would look like, so until we get some use cases and proposals I'll close this.
