### ISSUE TITLE
multiple top level dependencies showing from one dependency?

### ISSUE THREAD

**Issue by PhilipAbed** [tox-dev/pipdeptree#147]
Hi, 

I run "pip install jira" on a fresh environment
i see that its installing "PyJWT==2.0.1" and "cryptography==3.3.1"
i run pipdeptree and see image
![image](https://user-images.githubusercontent.com/42116482/106932239-2c9c7e80-6720-11eb-9553-238a43c8c305.png)

i see PyJWT==2.0.1 and cryptography==3.3.1 as top level dependencies and not children of jira==2.0.0
is that a bug? or am i missing something?

**Comment by naiquevin** [comment]
Are cryptography and PyJWT installed as optional/extra dependencies of jira by any chance? If yes, then can you please try running `pipdeptree.py` from the `idiot-z-add_extra_require` branch? 

That branch has work-in-progress code for supporting extra dependencies.

**Comment by gaborbernat** [comment]
I think this should be ok now.

**Comment by bac** [comment]
When installing `jira==2.0.0` I find that pipdeptree 2.3.1 still shows cryptography as a top-level package. From reading the discussion above I expected the issue to be resolved.
