### ISSUE TITLE
Version 2.2.1 on Windows installs into wrong directory, causing `file not found` errors

### ISSUE THREAD

**Issue by kerstin921** [tox-dev/pipdeptree#166]
I did `python -m pip install --upgrade pipdeptree` to install the package on a Windows 7 machine and it was installed into `C:\Program Files\Python38\Lib\site-packages\pipdeptree-2.2.1.dist-info\pipdeptree-2.2.1.dist-info` instead of just `C:\Program Files\Python38\Lib\site-packages\pipdeptree-2.2.1.dist-info`, causing `file not found` errors when trying to run it.

**Comment by kerstin921** [comment]
**HELLO???**

**Comment by naiquevin** [comment]
@kerstin921 Like any other python package, pipdeptree cannot control how/where it gets installed on a particular environment. It could be related to the behaviour of pip on Windows 7. I am not quite familiar with windows but 2 things come to mind for such problems: (1) admin privileges (2) sys.path  

You may also try specifying the `-t` option when running `pip install`.

**Comment by kerstin921** [comment]
Hi,

I already checked privileges and path variables, they're all perfectly set as I recently did a clean, system-wide reinstall of the entire Python framework. Can you at least reproduce this behavior and confirm/refute this is not a bug on your side?

**Comment by naiquevin** [comment]
Unfortunately I can't reproduce the issue completely as I don't have access to a windows 7 machine. I can try to reproduce it inside a virtualenv on linux.

Can you provide following info? 

* Version of python and pip 
* Previous version of pipdeptree that you upgraded from. 

At your end, can you also please try upgrading some other package to confirm that it's not your environment?

**Comment by kerstin921** [comment]
PS.: So, to answer your question, `pipdeptree` hasn't been upgraded from an older version either

**Comment by naiquevin** [comment]
Thanks for sharing the info. I tried reproducing this behaviour on linux with python version 3.8.0 and pip version 22.1.2, but couldn't. I tried both, installing the latest version with the `--upgrade` flag as well as actually upgrading from an older version of pipdeptree. In both cases, the files were copied to the expected location. 

I can see `pipdeptree` in the `pip list` output, which indicates that pip is able to find the package in spite of the incorrect location. Can you share the complete error output of `pipdeptree`. 

Also, `pipdeptree` doesn't depend on any other external packages, so it's unlikely that the version of any other package installed in your env could impact it.

**Comment by gaborbernat** [comment]
Seems this was fixed, and was a broken installation.
