### ISSUE TITLE
can pipdeptree help with packages listed by pip list but no longer installed?

### ISSUE THREAD

**Issue by piscvau** [tox-dev/pipdeptree#167]
I tried to use the package to create requirements file but I find out that the output of pip list includes many packages which are no longer used and cannot be uninstalled ; for example 
sudo pip3 uninstall python-apt
:Found existing installation: python-apt 2.0.0+ubuntu0.20.4.7
Not uninstalling python-apt at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'python-apt'. No files were found to uninstall.

After googling I think those packages need to be manually removed from /usr/lib/python3/dist-packages.
Is there a way to get a list of such packages ?

**Comment by gaborbernat** [comment]
We don't plan to support this.
