### ISSUE TITLE
Convert away from pkg_resources

### ISSUE THREAD

**Issue by matteius** [tox-dev/pipdeptree#175]
I was working on converting `pipenv` away from `pkg_resources` to use instead distributions from https://docs.python.org/3/library/importlib.metadata.htmland in the past hour it became problematic because we rely on `pipdeptree` which is expecting we are working with `pkg_resources` Distriubtions.   The problem as I see it is the pkg_resources documentation https://setuptools.pypa.io/en/latest/pkg_resources.html has this attention marker:

> Attention

> Use of pkg_resources is discouraged in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Please consider using those libraries instead of pkg_resources

I started working on this in the first place because of some edge case where some users cannot import pkg_resources.    Are there any plans to convert away from pkg_resources in this project?

**Comment by xiacunshun** [comment]
I noticed that there are also some pkg_resources used in source.
I think this need to be continued.

**Comment by gaborbernat** [comment]
PR for this is welcome 😊

**Comment by xiacunshun** [comment]
https://github.com/tox-dev/pipdeptree/pull/333

**Comment by xiacunshun** [comment]
I have submitted the code for this part, and due to API changes, the results may vary. Please help me with a code review, thank you. @gaborbernat

**Comment by xiacunshun** [comment]
I'll take a look at the failed test cases later, as I need to take a break first, haha.

**Comment by kemzeb** [comment]
Fixed by #333.
