### ISSUE TITLE
Offline option

### ISSUE THREAD

**Issue by gforcada** [tox-dev/pipdeptree#193]
Hi! 👋🏾 

Thanks for writing `pipdeptree` I'm loving it 😍 

I'm integrating it in https://github.com/plone repositories together with `z3c.dependencychecker` to understand and update the requirements of all distributions that make up Plone.

It would be cool if `pipdeptree` could have an `--offline` option where it would not require internet connection to resolve the dependencies.

My use case is that we have a `requirements.txt`/`constraints.txt` files with all the dependencies and their exact version that need to be used, we are missing the visualization of how they are tangled together (which is what `pipdeptree` covers ✨ ).

So the idea would be that when the `--offline` option is given to `pipdeptree` it resolves the dependencies within what's available within the virtual environment where it is run on.

If a dependency is missing/can't be resolved, `pipdeptree` needs to bail out and ask users to either remove the `--offline` option or install the packages that are needed.

Would this functionality something that make sense to have in `pipdeptree`? 🤔 🍀

**Comment by xiacunshun** [comment]
Indeed, `pipdeptree` can be used without network connection originally. It can also be used in virtual environment with `--local-only`.

**Comment by xiacunshun** [comment]
Could you post more outputs or steps to reporduce if you still have questions. Thanks!

**Comment by xiacunshun** [comment]
I closed this issue now.
If you still have problems, please reopen it anytime.
