### ISSUE TITLE
--graph-output any-of-them outputs a similar text result

### ISSUE THREAD

**Issue by gst** [tox-dev/pipdeptree#198]
Hi,

have installed most recent version (2.5.0), ubuntu focal, python 3.8, in a venv, having debian package graphviz 2.42.2 (python 0.20.1), imagemagick 8.

```
08:36 $ bash -c 'set -e ; for fmt in pdf jpeg png svg ; do pipdeptree --graph-output $fmt > result.${fmt} ; file result.${fmt} ; head -2 result.${fmt} ; done'
result.pdf: ASCII text
flowchart TD
    classDef missing stroke-dasharray: 5
result.jpeg: ASCII text
flowchart TD
    classDef missing stroke-dasharray: 5
result.png: ASCII text
flowchart TD
    classDef missing stroke-dasharray: 5
result.svg: ASCII text
flowchart TD
    classDef missing stroke-dasharray: 5
```

any idea what can be wrong on my side ?

Thx.

**Comment by Guts** [comment]
Same here.

**Comment by gst** [comment]
@Guts what is you env details ?

**Comment by Guts** [comment]
Sorry, my comment lacked of info:

```sh
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

- Imagemagick 8:6.9.11.60+dfsg-1.3build2
- graphviz 2.42.2-6

In a Python 3.10 venv:

- graphviz 0.20.1
- pipdeptree 2.5.0

**Comment by rez10191** [comment]
I think this issue was resolved in with this update: https://github.com/tox-dev/pipdeptree/issues/197

Looks like a new patch release for the package with this update would be required at this point.

Thanks to the authors for the great project here!

**Comment by gst** [comment]
Thanks for pointing the root cause @rez10191 :)

> Looks like a new patch release for the package with this update would be required at this point.

ah effectively, hopefully this can be done quickly ?

meanwhile I'll pin to previous version..

**Comment by kdeldycke** [comment]
`pipdeptree 2.5.1` has been released yesterday and should fix this issue. This ticket can be closed now.
