### ISSUE TITLE
pipdeptree -l is broken - doesn't seem to respect local virtualenv

### ISSUE THREAD

**Issue by prologic** [tox-dev/pipdeptree#2]
See: http://codepad.org/j5MwjQYt

There is some discrepancy here between what `pip freeze` thinks is local and what `pipdeptree -l` thinks is local.

**Comment by jonafato** [comment]
@naiquevin `virtualenvwrapper` has a hook called `postmkvirtualenv`. If you place an executable script with `pip install pipdeptree` in it at `$WORKON_HOME/postmkvirtualenv`, `pipdeptree` will be installed after the creation of each new virtualenv.

**Comment by naiquevin** [comment]
@jonafato This is really useful thanks. Will try it and also mention it in the README.

**Comment by gaborbernat** [comment]
This should be no longer the case.
