### ISSUE TITLE
PEP 658 as a way to speedup(?) package resolution

### ISSUE THREAD

**Issue by gforcada** [tox-dev/pipdeptree#236]
Seems that for a few days [PEP 658](https://peps.python.org/pep-0658/), [see announcement](https://discuss.python.org/t/pep-658-is-now-live-on-pypi/26693) is live on PyPi.

If I understand it right, this could mean that to do a full dependency resolution of a package one does not need to install anymore the packages, but only fetch their metadata.

There's one caveat though: it only works for wheels, packages only providing sdists will not be providing them.

Is this something that could be implemented/used here, or rather from _upstream_ in `pip`? 🤔

**Comment by gaborbernat** [comment]
This project works offline on what's installed not otherwise so this is not useful for us.
