### ISSUE TITLE
CLI Output Uses Unknown Unicode For Line Spacing 

### ISSUE THREAD

**Issue by dparkinson101** [tox-dev/pipdeptree#253]
![image](https://github.com/tox-dev/pipdeptree/assets/22814107/aab213c5-2868-4e6c-aa7e-ffd585193946)

The output for the tool uses unicode spacing which is not recognised when output in jenkins logs when you look at them through the web portal. This makes the log overall much messier and less readable. 

Suggestion to add an optional parameter that overrides the sys.out.encoding check for if you want to output with Unicode or not.

**Comment by gaborbernat** [comment]
PR welcome 👍

**Comment by dparkinson101** [comment]
Created a quick one: See [PR#254 ](https://github.com/tox-dev/pipdeptree/pull/254)
