### ISSUE TITLE
Unable to generate graph output due to incorrect arg parsing in 2.10.0

### ISSUE THREAD

**Issue by peter-kipping-seequent** [tox-dev/pipdeptree#269]
When running `pipdeptree --graph-output png > ./test.png` with the latest version (2.10.0)
We get the following error: **AttributeError: 'Namespace' object has no attribute 'graph_output'**

Full traceback:
![image](https://github.com/tox-dev/pipdeptree/assets/75957833/6e404870-19c4-4162-b574-e1ceb3c59723)

Suspect something to do with https://github.com/tox-dev/pipdeptree/blob/e86182613ac3e91630f88eb1f3767b3b64c37c4d/src/pipdeptree/_cli.py#L129 has caused the 'graph_output' field to not be set correctly as it appears its only getting assigned to the 'output_format' value. So not sure what the check at https://github.com/tox-dev/pipdeptree/blob/e86182613ac3e91630f88eb1f3767b3b64c37c4d/src/pipdeptree/_render/__init__.py#L24 is actually supposed to be checking anymore?

**Current work around:**
Currently pinning the version of pipdeptree back to 2.9.6 works fine for my use-case `pip install pipdeptree==2.9.6`. Doesn't look like 2.10.0 actually introduced any massive new functionality so hopefully this workaround will be fine for most people.

**Comment by peter-kipping-seequent** [comment]
For completeness, running with graphvis 0.20.1 in WSL running Ubuntu 22.04.2 with Python 3.11.

`pip install --compile graphviz pipdeptree`
![image](https://github.com/tox-dev/pipdeptree/assets/75957833/f407a365-5f3e-427e-b9a6-5ecd4e60579c)

**Comment by davidzhouwa** [comment]
Encountered the same, please release with a fix.

**Comment by gaborbernat** [comment]
This is an open source project, if your you are looking for a fix in a
short amount of time, you better put in a pull request.
