### ISSUE TITLE
pipdeptree user Python2

### ISSUE THREAD

**Issue by geeksailor** [tox-dev/pipdeptree#287]
Hello!
First I want to thank the devs for this wonderful tool. It has been very useful to see the packages I have installed for a project I am working on and using it to de-conflicting any modules that require the same package but different versions. 
So to getting down to my issue, to give a basic background I am running this tool on Ubuntu 20.04 in a virtual (vm) environment that has both Python 2.7 and Python 3.8.10 installed and I am using it to try and look at both root and user pip package dependencies. I have ran it successfully to get the dependencies being used by both version of Python for root as well as the dependencies for Python3 for my non-root user account. However, when I attempt to run pipdeptree to get the Python2 dependencies for the user it errors out. The command I am attempting to run is `pipdpipdeptree -u --python /usr/bin/python2` and the error I am getting is:
>Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 114, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/usr/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 281, in get_code
    self.code = compile(source, self.filename, 'exec')
  File "/tmp/tmp6otfc_ei/pipdeptree/__main__.py", line 14
    def main(args: Sequence[str] | None = None) -> None | int:
                 ^
SyntaxError: invalid syntax

Can anyone tell why it works ok for pip2 root but not user?
Thanks!

Edit 1:Not sure how I got it to work for root before but now Python2 for root is having the same issue as well.

Edit 2: I've been rooting around more and ran into issue https://github.com/tox-dev/pipdeptree/issues/50. I'm trying to see if that can help me any but it looks like it could be a problem with how the program itself is pointed and python is pointed?

**Comment by geeksailor** [comment]
Not sure how I got it to work for root before but now Python2 for root is having the same issue as well.

**Comment by geeksailor** [comment]
I've been rooting around more and ran into issue #50.  I'm trying to see if that can help me any but it looks like it could be a problem with how the program itself is pointed and python is pointed?

**Comment by gaborbernat** [comment]
We do not support Python 2.

**Comment by geeksailor** [comment]
@gaborbernat 
Gotcha, thank you for the quick response!

**Comment by sparrowt** [comment]
pipdeptree 2.2.0 is the last version for which there are python 2 wheels on pypi:
https://pypi.org/project/pipdeptree/2.2.0/#files

pipdeptree 2.2.1 only has a python 3 wheel: (although the code [should still support python 2](https://github.com/tox-dev/pipdeptree/blob/2.2.1/setup.py#L33))
https://pypi.org/project/pipdeptree/2.2.1/#files

pipdeptree 2.3.0 has dropped python 2.7 support:
https://github.com/tox-dev/pipdeptree/blob/a64ae4a5391bb59e50f809e5b3c6252811f4816c/pyproject.toml#L18
although there was nothing in the changelog:
https://github.com/tox-dev/pipdeptree/blob/2.3.0/CHANGES.md

**Comment by gaborbernat** [comment]
Yeah, we should be deleting that. The change log nowadays is exclusively kept on GitHub releases.

**Comment by sparrowt** [comment]
Yes I only dug it out on the old tag to see if it mentioned the py2 deprecation - there's no changelog file in `main`
