### ISSUE TITLE
Issue with packages built with pdm-backend 2.x

### ISSUE THREAD

**Issue by f3flight** [tox-dev/pipdeptree#324]
Hi tox-dev team, I've filed a bug to setuptools but it is related to pipdeptree (manifests through it), I think you may want to be aware - https://github.com/pypa/setuptools/issues/4250.
TL;DR is packages built with `pdm-backend` 2.x use unexpected normalization for `.dist-info` folder name, causing pipdeptree to fail mapping requrement to dist.

**Comment by gaborbernat** [comment]
Thanks 👏 is an upstream problem so closing.

**Comment by gaborbernat** [comment]
I feel we should normalize package names on our side, PR for that welcome. I don't think it's a setuptools bug.

**Comment by f3flight** [comment]
> I feel we should normalize package names on our side, PR for that welcome. I don't think it's a setuptools bug.
Right, my gut feeling is similar. I filed a bug to pdm-backend as well, because that is the source of change - https://github.com/pdm-project/pdm-backend/issues/218
