### ISSUE TITLE
Graphviz Not Recognized in Virtual Env on Mac M1

### ISSUE THREAD

**Issue by Fares-Harri** [tox-dev/pipdeptree#328]
Hi,

I'm using a Mac M1 and ran into a problem with `pipdeptree` in my virtual environment. Even after installing `graphviz` inside the virtual environment, I get an error when trying to use the `--graph-output` option. The error says `graphviz` isn't available.

I found a workaround by installing `graphviz` globally on my Mac, not just in the virtual environment. But, is this how it's supposed to work? Shouldn't installing `graphviz` inside the virtual environment be enough?

Thanks for your help,
Fares

**Comment by gaborbernat** [comment]
That shouldn't happen.

**Comment by kemzeb** [comment]
Hmm I'm using an M1 with macOS v14.3.1 and haven't been able to reproduce. After running the following commands in-order, I was able to output a PNG file without any issues:
- `brew install graphviz`
- `python3 -m venv venv`
- `source venv/bin/activate`
- `pip install pipdeptree graphviz`
- `pipdeptree --graph-output png`

**Comment by Fares-Harri** [comment]
@kemzeb that didn't worked with me not sure why, maybe the python version or installation tool make since not sure

I am using `pyenv` + `python 3.9.13`
