### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by ennamarie19** [tox-dev/pipdeptree#376]
Hello,
My name is McKenna Dallmeyer and I would like to submit pipdeptree to OSS-Fuzz.

If you are not familiar with the project, OSS-Fuzz is Google's platform for continuous fuzzing of Open Source Software.

In order to get the most out of this program, it would be greatly beneficial to be able to merge-in my fuzz harness and build scripts into the upstream repository and contribute bug fixes if they come up. Is this something that you would support me putting the effort into?

Thank you!

**Comment by kemzeb** [comment]
Hi @ennamarie19! I'll need to do some research on oss-fuzz (and fuzz testing in general) to see if this is something that would be useful to pipdeptree. When I get the time, I'll let you know what I think

**Comment by kemzeb** [comment]
Thank you for your patience @ennamarie19.

Having some understanding of oss-fuzz now, I don't believe we need it at this time seeing that this is a smaller project compared to some other projects I have seen using this service. This has however made me interested building fuzz tests for this project and I may dabble with it in the future.

Feel free to reopen this issue if you disagree.
