### ISSUE TITLE
support non-default /site-packages/

### ISSUE THREAD

**Issue by drzraf** [tox-dev/pipdeptree#408]
### Describe the feature

Like `pip freeze --path=<...>` allows so that packages installed from an old version of Python are supported.

**Comment by kemzeb** [comment]
This is reasonable. I also think an option like this should accept multiple paths.

As a workaround you can also use Python's `PYTHONPATH` environment variable to add these paths to `sys.path` (see [here](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) for details). It should also work if your using a virtual environment.
