### ISSUE TITLE
error message: "Warning!!! Missing or invalid metadata found in the following site dirs"

### ISSUE THREAD

**Issue by luckman212** [tox-dev/pipdeptree#409]
### What pipdeptree version are you using?

2.23.3

### Are you running pipdeptree in a virtual environment?

No

### Describe the problem

My system is macOS 14.6.1, and I have both Python 3.11 and 3.12 installed via Homebrew.

```
$ pipdeptree --version
2.23.3

$ python3.11 -V
Python 3.11.10

$ python3.12 -V
Python 3.12.6

$ command -v python3.11
/opt/homebrew/bin/python3.11

$ realpath $(command -v python3.11)
/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/bin/python3.11

$ command -v python3.12
/opt/homebrew/bin/python3.12

$ realpath $(command -v python3.12)
/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/bin/python3.12
```

I'm hitting an issue, apparently with my global site-packages dir, and looking for help identifying how to fix it.

```
$ pipdeptree --python /opt/homebrew/bin/python3.11
Warning!!! Missing or invalid metadata found in the following site dirs:  <==
/opt/homebrew/lib/python3.11/site-packages
{...rest of pipdeptree output...}
```

I see this warning message originates from the [`test_invalid_metadata()`][1] function in `tests/test_discovery.py` but I don't know how to drill down further into what's causing it or how to identify whatever condition is being flagged here.

It's worth noting that running the same command against my python3.12 interpreter does not produce any errors:

```
$ pipdeptree --python /opt/homebrew/bin/python3.12  <== ok
```

[1]: https://github.com/tox-dev/pipdeptree/blob/99b0b1272b363d42f31a98a58fc3f76475bb55c2/tests/test_discovery.py#L161

**Comment by kemzeb** [comment]
This warning means that there should be a `METADATA` file somewhere in `/opt/homebrew/lib/python3.11/site-packages` that is missing [required](https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-specifications) metadata. [Currently](https://github.com/tox-dev/pipdeptree/blob/99b0b1272b363d42f31a98a58fc3f76475bb55c2/src/pipdeptree/_discovery.py#L96) this just means you have a `METADATA` file somewhere in your site directory that is missing the `Name` field.

`importlib.metadata` (which we use to grab all the env's package metadata) doesn't validate this file and it doesn't appear to publicly expose the path to it; however, they do expose the site dir that the problem distribution package is a child of (which is what we see here).

All that happens in pipdeptree is that we skip this package, but if you want to you can search your site dir looking for `METADATA` files that don't contain a `Name` field.

**Comment by luckman212** [comment]
@kemzeb Thank you for trying to help.

But, I ran the commands below, which should find any `METADATA` files without a `Name:` field. However, it found none.

```
$ cd /opt/homebrew/lib/python3.11/site-packages
$ find . -type f -name METADATA -exec grep --files-without-match '^Name:' {} +
(...no output...)
```

**Comment by luckman212** [comment]
I used a bisect method to find the offending directory. Just took half of the dirs out of the site-packages dir and kept iterating, until I was left with just this:

<img src=https://github.com/user-attachments/assets/d3fac2cd-fa7f-4547-be81-b8d93389a485 width=491>

Seems to be some leftover dir from a failed install or upgrade. I nuked it and all was well.

If it helps, here's a script I came up with that should find both invalid as well as entirely _missing_ `METADATA` files, which also trigger this warning from pipdeptree.

```bash
#!/usr/bin/env bash

SITE_PACKAGES_DIR='/opt/homebrew/lib/python3.11/site-packages'

verify_metadata() {
  for f in "${METADATA_FILES[@]}"; do
    grep --files-without-match '^Name:' "$f";
    grep --files-without-match '^Metadata-Version:' "$f";
    grep --files-without-match '^Version:' "$f";
  done
}

missing_metadata() {
  find "$SITE_PACKAGES_DIR" -mindepth 1 -type d -name "*.dist-info" ! -exec sh -c 'test -f "$0/METADATA"' {} \; -print
}

mapfile -t METADATA_FILES < <(find "$SITE_PACKAGES_DIR" -type f -name METADATA)

mapfile -t INVALID_METADATA < <(verify_metadata)
if [[ -n ${INVALID_METADATA[0]} ]]; then
  echo 1>&2 "files containing INVALID metadata:"
  printf '%s\n' "${INVALID_METADATA[@]}"
fi

mapfile -t MISSING_METADATA < <(missing_metadata)
if [[ -n ${MISSING_METADATA[0]} ]]; then
  echo 1>&2 "dirs with MISSING metadata:"
  printf '%s\n' "${MISSING_METADATA[@]}"
fi
```

**Comment by kemzeb** [comment]
Was not aware `importlib.metadata` also accepted missing `METADATA` files. Glad you were able to solve this problem!

**Comment by edrozenberg** [comment]
> If it helps, here's a script I came up with that should find both invalid as well as entirely _missing_ `METADATA` files, which also trigger this warning from pipdeptree.

Very helpful! In my case I had an old leftover `pip-25.1.1.dist-info` dir (in addition to the current/valid `pip-25.2.dist-info` dir), and this old dir contained only a `RECORD` file. Your script helped me to ID this leftover dir, getting rid of it cleaned up the `pipdeptree` warning.
