### ISSUE TITLE
Case sensitivity issues

### ISSUE THREAD

**Issue by nicoulaj** [tox-dev/pipdeptree#77]
If I use this in a package:
```
install_requires=[ 'shapely==1.5.17.post1' ]
```
The package installs fine, but the pipdeptree graphviz output has an extra root node with `Shapely`.

Fixing my package to match the case for this library on pypi works around the issue (`install_requires=[ 'Shapely==1.5.17.post1' ]`)

**Comment by nicoulaj** [comment]
Another example: `scikit-image` requires `pillow` all lowercase, so you get an extra `Pillow` in the graph.

**Comment by sschuberth** [comment]
I'm seeing a similar issue for a project that depends on "Sphinx", and some transitive dependency depends on "sphinx". This seem to result in the `--json` output to contain the package in both spellings, but the latter has a version of `null`:

    {"package_name":"Sphinx","installed_version":"1.6.6"},{"package_name":"sphinx","installed_version":null}

**Comment by gaborbernat** [comment]
This should be no longer the case, if is please reopen.
