### ISSUE TITLE
combine --package with  --graph-output 

### ISSUE THREAD

**Issue by artgoldberg** [tox-dev/pipdeptree#87]
Dear Vineet and colleagues

Great idea and wonderful program! 
It would helpful to be able to plot the graph of antecedents to a package or set of packages.

Thanks
Arthur

**Comment by artgoldberg** [comment]
Also, it would be really neat to be able to output graphs into an interactive graph network viewer, like vis.js!

**Comment by naiquevin** [comment]
There was PR #65 for having `--graph-output` and `--json` respect `--packages` option. However, it had to be reverted as it broke the `--reverse`. Fixing it is on my list but the change will need some refactoring. For now I am busy with other stuff so can't promise when it will be done. 

For the second suggestion - I am not familiar with this tool but on first glance it looks good so I'd also be open to PR for this. Another approach is to feed the `pipdeptree --json` output to some a script that could convert it into the format that vis.js understands.

**Comment by ptrsny** [comment]
This would also be really great for the '-e' option witch seems to be respected only when used without '--graph-output'

**Comment by naiquevin** [comment]
Started working on this! Hoping to release a new version soon :-)

**Comment by naiquevin** [comment]
This is an old issue but just wanted to inform that this is now fixed in the `v2beta` branch. Planning to release a new "beta" version soon.

**Comment by ssbarnea** [comment]
Basically the fact `-p` does not work with output makes the graphing useless as it generates a huge graph that nobody can read.

**Comment by naiquevin** [comment]
@ssbarnea Its fixed in latest master. You'll need to upgrade to the beta version explicitly from PyPI 

```
pip install pipdeptree==2.0.0b1
```

**Comment by ssbarnea** [comment]
That is great news. Meanwhile I decided to go plain text via https://github.com/ansible/ansible-lint/pull/817 and avoid the image issues. Even so the plain text approach has the disadvantage of including version information, which in my case was not really needed.

Even so, now I know that if I have time to make a PR to optionally silence the version information, it will likely be accepted.

**Comment by kdeldycke** [comment]
I can attest `2.0.0b1` definitely fix the issue! 👍

**Comment by artgoldberg** [comment]
@naiquevin Thanks for your great work!
