### ISSUE TITLE
Suggest change `project_name` to lower case

### ISSUE THREAD

**Issue by zufuliu** [tox-dev/pipdeptree#99]
Suggest change `project_name` to lower case, since pip package name is case insensitive.
Packages like Pillow, Pygments and PyYAML often has different spellings in other package's dependency list. This will reduce isolated packages / dependencies produced by pipdeptree.

This change only need to add four lines in `build_dist_index`:
```python
    for p in pkgs:
        p.project_name = p.project_name.lower()
        for r in p.requires():
            r.project_name = r.project_name.lower()
    return dict((p.key, DistPackage(p)) for p in pkgs)
```

**Comment by naiquevin** [comment]
Can you please open a PR with both this one and #100? Will be easier to test and merge that way.

**Comment by zufuliu** [comment]
It's PR #102.

**Comment by sschuberth** [comment]
This sound like a duplicate of issue https://github.com/naiquevin/pipdeptree/issues/77.

**Comment by zufuliu** [comment]
@sschuberth It's a duplicate, do you have any idea to fix these failed tests in PR #102?

**Comment by naiquevin** [comment]
Tests could have failed for completely different reason. The tests have become complicated and messy and I am trying to sort it out. Will test this PR and merge it. Thanks.

**Comment by gaborbernat** [comment]
I think we should leave the package name normalization up to pip.
